### ISSUE TITLE
デプロイを自動化したい

### ISSUE THREAD

**Issue by uzimaru0000** [Zli-UoA/WebSite#30]
したくない？

**Comment by kusaoisii** [comment]
したい！nowスカ！

**Comment by kusaoisii** [comment]
逆にnowしかしらない...

**Comment by uzimaru0000** [comment]
nowでもいいと思う
[こんなの](https://www.netlify.com/)とかもある

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by uzimaru0000** [comment]
nowでいいか
とりあえず、Storybookと本番用のデプロイをできるようにしよう

**Comment by uzimaru0000** [comment]
GitHubActionsでCI/CDしてnowにデプロイって感じにする
